# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 06:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('end_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('placeholder_image_url', models.URLField(blank=True, default='', max_length=255, null=True)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('transcript', models.TextField(verbose_name='Transcript')),
                ('contents', models.TextField(verbose_name='Content')),
                ('stream_url', models.URLField(max_length=255, verbose_name='Stream URL')),
                ('youtube_url', models.URLField(max_length=255, verbose_name='YouTube URL')),
                ('is_live', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Broadcast',
                'verbose_name_plural': 'Broadcasts',
            },
        ),
        migrations.CreateModel(
            name='PushTokens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
                ('show_ids', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'PushToken',
                'verbose_name_plural': 'PushTokens',
            },
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placeholder_image_url', models.URLField(blank=True, default='', max_length=255, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Show',
                'verbose_name_plural': 'Shows',
            },
        ),
        migrations.AddField(
            model_name='broadcast',
            name='shows',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='show_broadcast', to='navalny_live.Show', verbose_name='Show of broadcast messages'),
        ),
    ]
