# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navalny_live', '0002_auto_20170813_1011'),
    ]
    operations = [
        migrations.AlterField(
            model_name='broadcast',
            name='stream_url',
            field=models.CharField(max_length=255, verbose_name='Stream URL'),
        ),
    ]
